apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: control-plane-argo
  namespace: argo
subjects:
  - kind: ServiceAccount
    name: control-plane
    namespace: control-plane
roleRef:
  kind: Role
  name: control-plane-argo
  apiGroup: rbac.authorization.k8s.io
